Parameters:
  AmiId:
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-arm64
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
  InstanceType:
    Default: t4g.micro
    Type: String
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
  SubnetId:
    Type: AWS::EC2::Subnet::Id
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:  ec2.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedEC2InstanceDefaultPolicy
      RoleName: !Sub ${AWS::StackName}
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref Role
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds: !Ref SecurityGroupIds
      SubnetId: !Ref SubnetId
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}
