AWSTemplateFormatVersion: '2010-09-09'
Resources:
  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub ${AWS::StackName}
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}
      WebsiteConfiguration:
        IndexDocument: index.html
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${Bucket}/*
            Principal:
              AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${OriginAccessIdentity}
  Distribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - BucketPolicy
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          DefaultTTL: 0
          ForwardedValues:
            QueryString: true
          MaxTTL: 0
          MinTTL: 0
          TargetOriginId: default
          ViewerProtocolPolicy : https-only
        Enabled: true
        Origins:
          - Id: default
            DomainName: !GetAtt Bucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OriginAccessIdentity}
